# Change these first
owner: codezillastudio # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Code Z
    check: "tcp-ping"
    url: https://7716-idx-code-zgit-1726561396504.cluster-23wp6v3w4jhzmwncf7crloq3kw.cloudworkstations.dev
    icon: https://i.imgur.com/68dykn3.png
    port: 7716
    ipv6: true
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org

    notifications: 
      - type: discord

status-website:
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"
  theme: night
  favicon: https://i.imgur.com/C3PrvnU.png
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://i.imgur.com/C3PrvnU.png
  name: CodeZilla
  introTitle: "CodeZilla Projectes"
  introMessage: All Rights Reserved © 2024 [**CodeZillaStudio**](https://discrd.gg/4ACjbbrAPZ)
  navbar:
    - title: Status
      href: /uptime
    - title: Discord
      href: https://discrd.gg/4ACjbbrAPZ
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n: 
  footer: All Rights Reserved © 2024 [**CodeZillaStudio**](https://discrd.gg/4ACjbbrAPZ)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
